app/models/artwork.rb, db/migrate/20200530033656_create_artworks.rb, db/schema.rb, test/models/artwork_test.rb
=> added the artwork model

app/models/gallery.rb, db/migrate/20200530034859_create_galleries.rb, db/schema.rb, test/models/gallery_test.rb
=> added the gallery model

app/models/collection.rb, app/models/favourite.rb, db/migrate/20200530034859_create_galleries.rb, db/migrate/20200530035947_create_favourites.rb, db/migrate/20200530040335_create_collections.rb, db/schema.rb, test/models/collection_test.rb, test/models/favourite_test.rb
=> added the fave and collection model

app/models/curate.rb, db/migrate/20200530040753_create_curates.rb, db/schema.rb, test/models/curate_test.rb
=> added the curate model

app/models/like.rb, db/migrate/20200530042234_create_likes.rb, db/schema.rb, test/models/like_test.rb
=> added the like model

app/models/artwork_tag.rb, app/models/tag.rb, db/migrate/20200530043244_create_tags.rb, db/migrate/20200530043249_create_artwork_tags.rb, db/schema.rb, test/models/artwork_tag_test.rb, test/models/tag_test.rb
=> added tags and artwork-tags model

app/models/follow.rb, app/models/followed_relationship.rb, app/models/tag.rb, app/models/user.rb, artbythebrush-crud.rtf, db/migrate/20200530051237_create_followed_relationships.rb, db/migrate/20200530052118_create_follows.rb, db/schema.rb, db/seeds.rb, test/models/follow_test.rb, test/models/followed_relationship_test.rb
review please and then we can move on
=> completed the models

app/controllers/artworks_controller.rb, app/views/artworks/index.html.erb, app/views/artworks/show.html.erb, config/routes.rb, test/controllers/artworks_controller_test.rb
hi guys need someone to review this code before we push it to the master repo please
=> Artworks controller

app/controllers/artworks_controller.rb, app/views/artworks/new.html.erb
completed all the cru actions mind the d and they all have the views on artworks ready to be working on the front end
=> Remaining crud artwork

app/assets/stylesheets/components/_cards.scss, app/views/artworks/index.html.erb
hi, guys, i build out the basic view for the artwork let me know how it goes
=> built out the card display

app/controllers/artworks_controller.rb, app/views/artworks/_form.html.erb, app/views/artworks/index.html.erb, app/views/artworks/new.html.erb
made the view work on create and a link from the index
=> Refine artwork controller

app/views/artworks/index.html.erb
=> fixed up an error

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/views/layouts/application.html.erb, app/views/shared/_navbar.html.erb
=> second changes in the nav-bar

app/models/collection_favourite.rb, db/migrate/20200530040335_create_collections.rb, db/migrate/20200609102509_create_collection_favourites.rb, db/migrate/20200609104215_add_user_to_collection.rb, db/schema.rb, test/models/collection_favourite_test.rb
=> made some changes to fit the user story for our project

app/controllers/collection_favourites_controller.rb, config/routes.rb, test/controllers/collection_favourites_controller_test.rb
already reviewed with daniel going to push the code no errors found when testing
=> added the collection favourite controller

app/controllers/collections_controller.rb, config/routes.rb
informed the team and ensured to potential errors that could arise to when pushing it to the master branch
=> added the controller and routes for collections

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_galleries.scss, app/assets/stylesheets/pages/_index.scss, app/views/galleries/index.html.erb
=> first part gallery page

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
major refactor here and its now easier to work with going forward
=> Fixing nav bar

app/controllers/artwork_tags_controller.rb, app/controllers/artworks_controller.rb, app/controllers/collection_favourites_controller.rb, app/controllers/collections_controller.rb, app/controllers/favourites_controller.rb, app/controllers/follows_controller.rb, app/controllers/galleries_controller.rb, app/controllers/likes_controller.rb, app/controllers/pages_controller.rb, app/views/collection_favourites/index.html.erb, db/schema.rb
hey guys need someone to review this before merging into the main code base please
=> Refactor controllers

app/controllers/galleries_controller.rb, app/models/gallery.rb, app/views/galleries/_form.html.erb, app/views/galleries/new.html.erb, app/views/galleries/show.html.erb
got the background image to work
=> completed the backend

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_artworks.scss, app/assets/stylesheets/pages/_galleries.scss, app/controllers/pages_controller.rb, app/javascript/packs/application.js, app/views/artworks/_form.html.erb, app/views/galleries/_form.html.erb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/pages/profile.html.erb, app/views/shared/_collection_modal.html.erb, app/views/shared/_like_button.html.erb, app/views/shared/_navbar.html.erb
hey daniel i did all i could for tonight here
we got pretty much every thing except for the stuff i gotta copy from marties scss and had to figure the other stuff but here you go and see you tomorrow morning
=> Scss styling

app/controllers/artworks_controller.rb
fixed up the bug for the collections error on artwork show
=> fixed up the bug on artwork show with by adding a @collections

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_index.scss, app/controllers/artworks_controller.rb, app/javascript/packs/application.js, app/javascript/packs/form.js, app/views/artworks/_form.html.erb, app/views/artworks/new.html.erb
applied all the changes from the feedback given from marty please review and check off the merge
=> Implement martys front end feedback

app/models/artwork.rb, app/models/collection.rb, app/models/gallery.rb
Hi Daniel, can't believe I forgot to add the validations on the models for all our webforms now I done it all for all the ones that we needed but I will wait til you finish galleries so that we can get all that sorted
=> Adding validations models

app/assets/stylesheets/pages/_galleries.scss, app/views/galleries/index.html.erb
Finished Cards, Index Page. Just need to populate images into card
=> Finished Gallery Index Page

app/views/pages/home.html.erb, app/views/pages/profile.html.erb, db/seeds.rb
Reverts DanielNguyen8/artbythebrush#116
=> Revert "Done Some Seeds"

app/views/pages/home.html.erb
Reverts DanielNguyen8/artbythebrush#115
=> Revert "removed the unlink style"

app/views/artworks/show.html.erb, app/views/galleries/_form.html.erb, app/views/galleries/index.html.erb, app/views/galleries/new.html.erb, app/views/galleries/show.html.erb, app/views/pages/home.html.erb
Reverts DanielNguyen8/artbythebrush#118
=> Revert "Quick loading"

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/pages/_artworks.scss, app/views/artworks/_form.html.erb, app/views/artworks/show.html.erb, app/views/galleries/new.html.erb, app/views/pages/home.html.erb
hey man would you be able to pull this branch i just made sure things look alot nicer going forward for the forms and artwork show
=> Inspection sweeps

app/controllers/artworks_controller.rb, app/controllers/pages_controller.rb, app/views/artworks/show.html.erb, app/views/pages/profile.html.erb
Fix Artworks Belonging to the right user
=> Fix Artworks Belong to the right user

app/views/pages/home.html.erb
=> fixed up the index page before signing
